### ISSUE TITLE
连接不了bot

### ISSUE THREAD

**Issue by fenglianwanmao** [Timmy-web/Poe-Telegram-Chatbot#2]
![无标题1](https://github.com/Timmy-web/Poe-Telegram-Chatbot/assets/125185864/390b4f83-0c91-4f54-b5c5-29c753ae80ec)
我已在botfather那生成了token并替换了

**Comment by Timmy-web** [comment]
> ![无标题1](https://github.com/Timmy-web/Poe-Telegram-Chatbot/assets/125185864/390b4f83-0c91-4f54-b5c5-29c753ae80ec)
> 
> 我已在botfather那生成了token并替换了

看看export bot token那里如果不加引号可以吗？ 看起来好像是引号多了。因为我自己是docker部署，所以也没试过。

**Comment by fenglianwanmao** [comment]
> > ![无标题1](https://private-user-images.githubusercontent.com/125185864/317662040-390b4f83-0c91-4f54-b5c5-29c753ae80ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTg2MjYsIm5iZiI6MTcxMTYxODMyNiwicGF0aCI6Ii8xMjUxODU4NjQvMzE3NjYyMDQwLTM5MGI0ZjgzLTBjOTEtNGY1NC1iNWM1LTI5Yzc1M2FlODBlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwOTMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2MwNTdiYzc2OGM3MzdhMDRiYWQwOTJiMTg1MzVhNDc3ZTY0ZGM1YThhZjZmZmIwNjc5OGE3ZWMzNTQ0NGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jgX4h2JHzIyZGtHZamxSYCE_PoWrd5eKhkvbPtRmx5o)
> > 我已在botfather那生成了token并替换了
> 
> 看看export bot token那里如果不加引号可以吗？ 看起来好像是引号多了。因为我自己是docker部署，所以也没试过。

不行喔，我试试看docker吧

**Comment by fenglianwanmao** [comment]
> > ![无标题1](https://private-user-images.githubusercontent.com/125185864/317662040-390b4f83-0c91-4f54-b5c5-29c753ae80ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjMwMzUsIm5iZiI6MTcxMTYyMjczNSwicGF0aCI6Ii8xMjUxODU4NjQvMzE3NjYyMDQwLTM5MGI0ZjgzLTBjOTEtNGY1NC1iNWM1LTI5Yzc1M2FlODBlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMDQ1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGJhZGQ3MWMyN2Q5YTgxYjJhYjQ4OTc2ZWJiYjBhMWFlYTEwZmM0MTcwZWJlODFmMWUxOTk5YjgyNjc2M2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dGCiSkAe6ilTuWtmbAPxiSuFTtUyKXXwVGF2EHaw4S8)
> > 我已在botfather那生成了token并替换了
> 
> 看看export bot token那里如果不加引号可以吗？ 看起来好像是引号多了。因为我自己是docker部署，所以也没试过。

试过了，docker可以，谢谢
