### ISSUE TITLE
docker-compose logs中文乱码，这个怎么解决？

### ISSUE THREAD

**Issue by canwushuang** [Timmy-web/Poe-Telegram-Chatbot#3]
字母数字显示正确，中文显示为方块问号。docker版本是24.0.7
试过env设置C.UTF-8等网上的方法，也问了GPT3-4。依然没有很好解决。

**Comment by Timmy-web** [comment]
> 字母数字显示正确，中文显示为方块问号。docker版本是24.0.7
> 
> 试过env设置C.UTF-8等网上的方法，也问了GPT3-4。依然没有很好解决。

我的命令`docker logs poebot`或者`docker compose logs`都能正常看log没问题。
> docker版本24.0.7
docker compose版本v2.21.0

**Comment by canwushuang** [comment]
> > 字母数字显示正确，中文显示为方块问号。docker版本是24.0.7
> > 试过env设置C.UTF-8等网上的方法，也问了GPT3-4。依然没有很好解决。
> 
> 我的命令`docker logs poebot`或者`docker compose logs`都能正常看log没问题。
> 
> > docker版本24.0.7
> > docker compose版本v2.21.0

感谢！一直没留意是compose的问题，在docker和python logging编码上瞎折腾。原来是docker compose apt安装导致版本过低。替换新的bin文件即可解决乱码问题。

**Comment by Timmy-web** [comment]
> > > 字母数字显示正确，中文显示为方块问号。docker版本是24.0.7
> 
> > > 试过env设置C.UTF-8等网上的方法，也问了GPT3-4。依然没有很好解决。
> 
> > 
> 
> > 我的命令`docker logs poebot`或者`docker compose logs`都能正常看log没问题。
> 
> > 
> 
> > > docker版本24.0.7
> 
> > > docker compose版本v2.21.0
> 
> 
> 
> 感谢！一直没留意是compose的问题，在docker和python logging编码上瞎折腾。原来是docker compose apt安装导致版本过低。替换新的bin文件即可解决乱码问题。

按理说现在安装的docker都是自带compose，我都好久没见过`docker-compose`运行了，新版本都是不需要`-`，直接`docker compose`就好
